server:
  port: 8090

spring:
  application:
    name: spring-boot-mongodb-demo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demoDb
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
